# Generated by Django 5.1.3 on 2024-12-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('examples', models.JSONField(help_text="Provide examples in the format: [{'input': '...', 'output': '...', 'explanation': '...'}, ...]")),
                ('class_name', models.CharField(max_length=50)),
                ('method_name', models.CharField(max_length=50)),
                ('default_code', models.JSONField(help_text="Provide the default code as a dictionary, e.g., {'python': '...', 'cpp': '...', 'java': '...'}.")),
                ('constraints', models.TextField(blank=True, help_text='Optional: Specify constraints like input size, time limits, etc.')),
                ('followup', models.TextField(blank=True, help_text='Optional: Add follow-up questions or problem extensions.')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problems', models.ManyToManyField(to='problem_management.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='Provide arguments in json')),
                ('expected_output', models.JSONField(help_text='Provide expected output in json')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_management.problem')),
            ],
        ),
    ]
