# Generated by Django 5.1.3 on 2024-12-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_format',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_format',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_output',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='problem',
            name='example_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='example_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
